//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Client.UI.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Client.UI.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string FIELD_BIRTH_DATE {
            get {
                return ResourceManager.GetString("FIELD_BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string FIELD_EMAIL {
            get {
                return ResourceManager.GetString("FIELD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps page.
        /// </summary>
        public static string MODULE_PAGE_APPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_APPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string MODULE_PAGE_APPS_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_APPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games page.
        /// </summary>
        public static string MODULE_PAGE_GAMES_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_GAMES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string MODULE_PAGE_GAMES_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_GAMES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string MODULE_PAGE_HOME_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_HOME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MODULE_PAGE_HOME_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile page.
        /// </summary>
        public static string MODULE_PAGE_PROFILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_PROFILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MODULE_PAGE_PROFILE_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_PROFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop page.
        /// </summary>
        public static string MODULE_PAGE_SHOP_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_SHOP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string MODULE_PAGE_SHOP_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_SHOP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset value.
        /// </summary>
        public static string UNSET_STRING_VALUE {
            get {
                return ResourceManager.GetString("UNSET_STRING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field has an incorrect date value..
        /// </summary>
        public static string VALIDATION_ERROR_INVALID_DATE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be lesser than {0}.
        /// </summary>
        public static string VALIDATION_ERROR_MAX_DATE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MAX_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string VALIDATION_ERROR_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_REQUIRED_FIELD", resourceCulture);
            }
        }
    }
}
