//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Client.UI.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Client.UI.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All games and apps.
        /// </summary>
        public static string ALL_GAMES_AND_APPS {
            get {
                return ResourceManager.GetString("ALL_GAMES_AND_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add date.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_ADD_DATE {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_ADD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_POPULARITY {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_POPULARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_RATING {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_RELEASE_DATE {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_RELEASE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_TITLE {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_USE {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation code is invalid..
        /// </summary>
        public static string CONFIRMATION_CODE_IS_INVALID {
            get {
                return ResourceManager.GetString("CONFIRMATION_CODE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to {0}. Check your email for the verification code and enter it below.
        /// </summary>
        public static string CONFIRMATION_EMAIL_MESSAGE {
            get {
                return ResourceManager.GetString("CONFIRMATION_EMAIL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call has been placed to {0}. Check your phone for a flash (missed) call and enter the last {1} digits of the call number.
        /// </summary>
        public static string CONFIRMATION_FLASH_CALL_MESSAGE {
            get {
                return ResourceManager.GetString("CONFIRMATION_FLASH_CALL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMS has been sent to {0}. Check your phone’s SMS for the verification code and enter it below.
        /// </summary>
        public static string CONFIRMATION_SMS_MESSAGE {
            get {
                return ResourceManager.GetString("CONFIRMATION_SMS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail field is required..
        /// </summary>
        public static string EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code.
        /// </summary>
        public static string ENTER_THE_CODE {
            get {
                return ResourceManager.GetString("ENTER_THE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string EXECUTABLE_MODE_APPLICATION {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Op Lan.
        /// </summary>
        public static string EXECUTABLE_MODE_CO_OP {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_CO_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Op Online.
        /// </summary>
        public static string EXECUTABLE_MODE_CO_OP_ONLINE {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_CO_OP_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free To Play.
        /// </summary>
        public static string EXECUTABLE_MODE_FREE_TO_PLAY {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_FREE_TO_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Trial.
        /// </summary>
        public static string EXECUTABLE_MODE_FREE_TRIAL {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_FREE_TRIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string EXECUTABLE_MODE_GAME {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lan Multiplayer.
        /// </summary>
        public static string EXECUTABLE_MODE_MULTIPLAYER {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_MULTIPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Purchase.
        /// </summary>
        public static string EXECUTABLE_MODE_ONE_TIME_PURCHASE {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_ONE_TIME_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Multiplayer.
        /// </summary>
        public static string EXECUTABLE_MODE_ONLINE {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Subscription.
        /// </summary>
        public static string EXECUTABLE_MODE_REQUIRES_SUBSCRIPTION {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_REQUIRES_SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string EXECUTABLE_MODE_SETTINGS {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        public static string EXECUTABLE_MODE_SINGLE_PLAYER {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_SINGLE_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Screen.
        /// </summary>
        public static string EXECUTABLE_MODE_SPLIT_SCREEN_MULTIPLAYER {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_SPLIT_SCREEN_MULTIPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string EXECUTABLE_MODE_UTILITY {
            get {
                return ResourceManager.GetString("EXECUTABLE_MODE_UTILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string FIELD_BIRTH_DATE {
            get {
                return ResourceManager.GetString("FIELD_BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string FIELD_EMAIL {
            get {
                return ResourceManager.GetString("FIELD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Code.
        /// </summary>
        public static string GET_CODE {
            get {
                return ResourceManager.GetString("GET_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GIN_GEN_SEARCH {
            get {
                return ResourceManager.GetString("GIN_GEN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active applications.
        /// </summary>
        public static string GIZ_ACTIVE_APPS_TITLE {
            get {
                return ResourceManager.GetString("GIZ_ACTIVE_APPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items.
        /// </summary>
        public static string GIZ_APPS_ALL_ITEMS {
            get {
                return ResourceManager.GetString("GIZ_APPS_ALL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string GIZ_APPS_AUTO_START {
            get {
                return ResourceManager.GetString("GIZ_APPS_AUTO_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string GIZ_APPS_CATEGORY {
            get {
                return ResourceManager.GetString("GIZ_APPS_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string GIZ_APPS_DATE_ADDED {
            get {
                return ResourceManager.GetString("GIZ_APPS_DATE_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string GIZ_APPS_LAUNCH {
            get {
                return ResourceManager.GetString("GIZ_APPS_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string GIZ_APPS_LINKS {
            get {
                return ResourceManager.GetString("GIZ_APPS_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string GIZ_APPS_LOADING {
            get {
                return ResourceManager.GetString("GIZ_APPS_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string GIZ_APPS_MEDIA {
            get {
                return ResourceManager.GetString("GIZ_APPS_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New releases.
        /// </summary>
        public static string GIZ_APPS_NEW_RELEASES {
            get {
                return ResourceManager.GetString("GIZ_APPS_NEW_RELEASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:.
        /// </summary>
        public static string GIZ_APPS_PARAMETERS {
            get {
                return ResourceManager.GetString("GIZ_APPS_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Files.
        /// </summary>
        public static string GIZ_APPS_PERSONAL_FILES {
            get {
                return ResourceManager.GetString("GIZ_APPS_PERSONAL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Mode.
        /// </summary>
        public static string GIZ_APPS_PLAYER_MODE {
            get {
                return ResourceManager.GetString("GIZ_APPS_PLAYER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular items.
        /// </summary>
        public static string GIZ_APPS_POPULAR_ITEMS {
            get {
                return ResourceManager.GetString("GIZ_APPS_POPULAR_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string GIZ_APPS_PUBLISHER {
            get {
                return ResourceManager.GetString("GIZ_APPS_PUBLISHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added.
        /// </summary>
        public static string GIZ_APPS_RECENTLY_ADDED {
            get {
                return ResourceManager.GetString("GIZ_APPS_RECENTLY_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string GIZ_APPS_RELEASE_DATE {
            get {
                return ResourceManager.GetString("GIZ_APPS_RELEASE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string GIZ_APPS_REPAIR {
            get {
                return ResourceManager.GetString("GIZ_APPS_REPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application version.
        /// </summary>
        public static string GIZ_APPS_SELECT_EXE {
            get {
                return ResourceManager.GetString("GIZ_APPS_SELECT_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate.
        /// </summary>
        public static string GIZ_APPS_TERMINATE {
            get {
                return ResourceManager.GetString("GIZ_APPS_TERMINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update e-mail.
        /// </summary>
        public static string GIZ_CHANGE_EMAIL_TITLE {
            get {
                return ResourceManager.GetString("GIZ_CHANGE_EMAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string GIZ_CHANGE_PASSWORD_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_CHANGE_PASSWORD_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string GIZ_CHANGE_PASSWORD_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_CHANGE_PASSWORD_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string GIZ_CHANGE_PASSWORD_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_CHANGE_PASSWORD_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code should have {0} digits!.
        /// </summary>
        public static string GIZ_CONFIRMATION_CODE_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("GIZ_CONFIRMATION_CODE_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string GIZ_GEN_ADS {
            get {
                return ResourceManager.GetString("GIZ_GEN_ADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string GIZ_GEN_ALL {
            get {
                return ResourceManager.GetString("GIZ_GEN_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string GIZ_GEN_AND {
            get {
                return ResourceManager.GetString("GIZ_GEN_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to {0}.
        /// </summary>
        public static string GIZ_GEN_BACK_TO {
            get {
                return ResourceManager.GetString("GIZ_GEN_BACK_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string GIZ_GEN_BALANCE {
            get {
                return ResourceManager.GetString("GIZ_GEN_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GIZ_GEN_CANCEL {
            get {
                return ResourceManager.GetString("GIZ_GEN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string GIZ_GEN_CONFIRM {
            get {
                return ResourceManager.GetString("GIZ_GEN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string GIZ_GEN_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_GEN_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string GIZ_GEN_CONTINUE {
            get {
                return ResourceManager.GetString("GIZ_GEN_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string GIZ_GEN_EMAIL {
            get {
                return ResourceManager.GetString("GIZ_GEN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string GIZ_GEN_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("GIZ_GEN_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string GIZ_GEN_ENTER_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_GEN_ENTER_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string GIZ_GEN_MOBILE_PHONE {
            get {
                return ResourceManager.GetString("GIZ_GEN_MOBILE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string GIZ_GEN_OR {
            get {
                return ResourceManager.GetString("GIZ_GEN_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string GIZ_GEN_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_GEN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string GIZ_GEN_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("GIZ_GEN_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string GIZ_GEN_POINTS {
            get {
                return ResourceManager.GetString("GIZ_GEN_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular items.
        /// </summary>
        public static string GIZ_GEN_POPULAR_ITEMS {
            get {
                return ResourceManager.GetString("GIZ_GEN_POPULAR_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string GIZ_GEN_REPEAT_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_GEN_REPEAT_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send.
        /// </summary>
        public static string GIZ_GEN_RESEND {
            get {
                return ResourceManager.GetString("GIZ_GEN_RESEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        public static string GIZ_GEN_RESULTS_FOR {
            get {
                return ResourceManager.GetString("GIZ_GEN_RESULTS_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GIZ_GEN_SAVE {
            get {
                return ResourceManager.GetString("GIZ_GEN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string GIZ_GEN_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("GIZ_GEN_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string GIZ_GEN_SORT_BY {
            get {
                return ResourceManager.GetString("GIZ_GEN_SORT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string GIZ_GEN_TIME {
            get {
                return ResourceManager.GetString("GIZ_GEN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string GIZ_GEN_UPDATE {
            get {
                return ResourceManager.GetString("GIZ_GEN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string GIZ_GEN_USERNAME {
            get {
                return ResourceManager.GetString("GIZ_GEN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string GIZ_GEN_VERIFY {
            get {
                return ResourceManager.GetString("GIZ_GEN_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string GIZ_GEN_VIEW_DETAILS {
            get {
                return ResourceManager.GetString("GIZ_GEN_VIEW_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_ADD_TO_CART {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games &amp; Apps.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_GAMES_AND_APPS {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_GAMES_AND_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_LAUNCH {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t find anything.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_NO_RESULTS_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_NO_RESULTS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try different keywords or make sure everything is spelled correctly..
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_NO_RESULTS_RETRY_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_NO_RESULTS_RETRY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search games, apps, shop.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_SHOP {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_SHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string GIZ_GLOBAL_SEARCH_SHOW_ALL {
            get {
                return ResourceManager.GetString("GIZ_GLOBAL_SEARCH_SHOW_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a member?.
        /// </summary>
        public static string GIZ_LOGIN_ALREADY_A_MEMBER {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_ALREADY_A_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot you password?.
        /// </summary>
        public static string GIZ_LOGIN_FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member?.
        /// </summary>
        public static string GIZ_LOGIN_NOT_A_MEMBER {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_NOT_A_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string GIZ_LOGIN_OR {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan this with the Mobile app to sign in instantly.
        /// </summary>
        public static string GIZ_LOGIN_QR_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_QR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with QR Code.
        /// </summary>
        public static string GIZ_LOGIN_QR_TITLE {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_QR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you log in now, you will be automatically logged out at the specified time..
        /// </summary>
        public static string GIZ_LOGIN_RESERVATION_WARNING_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_RESERVATION_WARNING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer is reserved at {0}..
        /// </summary>
        public static string GIZ_LOGIN_RESERVATION_WARNING_TITLE {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_RESERVATION_WARNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string GIZ_LOGIN_SIGN_IN_TITLE {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_SIGN_IN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        public static string GIZ_LOGIN_SIGN_UP_NOW {
            get {
                return ResourceManager.GetString("GIZ_LOGIN_SIGN_UP_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Hidden.
        /// </summary>
        public static string GIZ_MENU_BALANCE_IS_HIDDEN {
            get {
                return ResourceManager.GetString("GIZ_MENU_BALANCE_IS_HIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time product.
        /// </summary>
        public static string GIZ_MENU_TIME_PRODUCT {
            get {
                return ResourceManager.GetString("GIZ_MENU_TIME_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found for.
        /// </summary>
        public static string GIZ_NO_MATCH_FOUND_FOR {
            get {
                return ResourceManager.GetString("GIZ_NO_MATCH_FOUND_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try formulating your request differently.
        /// </summary>
        public static string GIZ_NO_MATCH_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_NO_MATCH_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as all read.
        /// </summary>
        public static string GIZ_NOTIFICATIONS_MARK_ALL_AS_READ {
            get {
                return ResourceManager.GetString("GIZ_NOTIFICATIONS_MARK_ALL_AS_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        public static string GIZ_NOTIFICATIONS_MARK_AS_READ {
            get {
                return ResourceManager.GetString("GIZ_NOTIFICATIONS_MARK_AS_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new notifications..
        /// </summary>
        public static string GIZ_NOTIFICATIONS_NO_NEW_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("GIZ_NOTIFICATIONS_NO_NEW_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When something new happens you’ll find it here..
        /// </summary>
        public static string GIZ_NOTIFICATIONS_NO_NEW_NOTIFICATIONS_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_NOTIFICATIONS_NO_NEW_NOTIFICATIONS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string GIZ_NOTIFICATIONS_TITLE {
            get {
                return ResourceManager.GetString("GIZ_NOTIFICATIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Password.
        /// </summary>
        public static string GIZ_PASSWORD_MESSAGE_SECURE {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_MESSAGE_SECURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too easy.
        /// </summary>
        public static string GIZ_PASSWORD_MESSAGE_TOO_EASY {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_MESSAGE_TOO_EASY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short.
        /// </summary>
        public static string GIZ_PASSWORD_MESSAGE_TOO_SHORT {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_MESSAGE_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the e-mail that is linked to your account.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number that is linked to your account.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_ENTER_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_ENTER_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_ENTER_YOUR_CODE {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_ENTER_YOUR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code from the text message we sent to {0}.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_PLEASE_ENTER_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_PLEASE_ENTER_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! Now come up with a new password and you&apos;re all set.
        /// </summary>
        public static string GIZ_PASSWORD_RECOVERY_SET_PASSWORD_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RECOVERY_SET_PASSWORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-24 characters.
        /// </summary>
        public static string GIZ_PASSWORD_RULE_LENGTH {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RULE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 lowercace letter.
        /// </summary>
        public static string GIZ_PASSWORD_RULE_LOWER_CASE {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RULE_LOWER_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 number.
        /// </summary>
        public static string GIZ_PASSWORD_RULE_NUMBER {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RULE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 uppercase letter.
        /// </summary>
        public static string GIZ_PASSWORD_RULE_UPPER_CASE {
            get {
                return ResourceManager.GetString("GIZ_PASSWORD_RULE_UPPER_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string GIZ_REGISTRATION_ENTER_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("GIZ_REGISTRATION_ENTER_YOUR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile phone.
        /// </summary>
        public static string GIZ_REGISTRATION_ENTER_YOUR_MOBILE_PHONE {
            get {
                return ResourceManager.GetString("GIZ_REGISTRATION_ENTER_YOUR_MOBILE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your country code and enter your phone number to create an account..
        /// </summary>
        public static string GIZ_REGISTRATION_MOBILE_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_REGISTRATION_MOBILE_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string GIZ_REGISTRATION_SIGN_UP_BUTTON {
            get {
                return ResourceManager.GetString("GIZ_REGISTRATION_SIGN_UP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string GIZ_REGISTRATION_SIGN_UP_TITLE {
            get {
                return ResourceManager.GetString("GIZ_REGISTRATION_SIGN_UP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string GIZ_REGISTRATION_SIGN_ΙΝ {
            get {
                return ResourceManager.GetString("GIZ_REGISTRATION_SIGN_ΙΝ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string GIZ_SHOP_ADD_TO_CART {
            get {
                return ResourceManager.GetString("GIZ_SHOP_ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle includes:.
        /// </summary>
        public static string GIZ_SHOP_CARD_BUNDLE_BUNDLE_INCLUDES {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CARD_BUNDLE_BUNDLE_INCLUDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action period.
        /// </summary>
        public static string GIZ_SHOP_CARD_TIME_PRODUCT_ACTION_PERIOD {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CARD_TIME_PRODUCT_ACTION_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package description:.
        /// </summary>
        public static string GIZ_SHOP_CARD_TIME_PRODUCT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CARD_TIME_PRODUCT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product life time.
        /// </summary>
        public static string GIZ_SHOP_CARD_TIME_PRODUCT_LIFE_TIME {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CARD_TIME_PRODUCT_LIFE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for you order!.
        /// </summary>
        public static string GIZ_SHOP_CHECKOUT_COMPLETE_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CHECKOUT_COMPLETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You can see all your current orders under My Profile &gt; Purchased.
        /// </summary>
        public static string GIZ_SHOP_CHECKOUT_COMPLETE_NOTE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CHECKOUT_COMPLETE_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting Place order, you accept the Gizmo Customer Agreement and privacy statement and represent that you have the authority to do so..
        /// </summary>
        public static string GIZ_SHOP_CHECKOUT_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CHECKOUT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string GIZ_SHOP_CHECKOUT_TITLE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_CHECKOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned points.
        /// </summary>
        public static string GIZ_SHOP_EARNED_POINTS {
            get {
                return ResourceManager.GetString("GIZ_SHOP_EARNED_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products.
        /// </summary>
        public static string GIZ_SHOP_NO_PRODUCTS_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_NO_PRODUCTS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add products to get started.
        /// </summary>
        public static string GIZ_SHOP_NO_PRODUCTS_RETRY_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_NO_PRODUCTS_RETRY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order comments.
        /// </summary>
        public static string GIZ_SHOP_ORDER_NOTE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_ORDER_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your note...
        /// </summary>
        public static string GIZ_SHOP_ORDER_NOTE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GIZ_SHOP_ORDER_NOTE_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My order.
        /// </summary>
        public static string GIZ_SHOP_ORDER_TITLE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_ORDER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string GIZ_SHOP_PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("GIZ_SHOP_PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        public static string GIZ_SHOP_PLACE_ORDER {
            get {
                return ResourceManager.GetString("GIZ_SHOP_PLACE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string GIZ_SHOP_PRICE {
            get {
                return ResourceManager.GetString("GIZ_SHOP_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string GIZ_SHOP_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("GIZ_SHOP_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string GIZ_SHOP_QUANTITY {
            get {
                return ResourceManager.GetString("GIZ_SHOP_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related products.
        /// </summary>
        public static string GIZ_SHOP_RELATED_PRODUCTS {
            get {
                return ResourceManager.GetString("GIZ_SHOP_RELATED_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string GIZ_SHOP_SUBTOTAL {
            get {
                return ResourceManager.GetString("GIZ_SHOP_SUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string GIZ_SHOP_TOTAL {
            get {
                return ResourceManager.GetString("GIZ_SHOP_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string GIZ_SYSTEM_LOCKED {
            get {
                return ResourceManager.GetString("GIZ_SYSTEM_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string GIZ_SYSTEM_VERSION {
            get {
                return ResourceManager.GetString("GIZ_SYSTEM_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string GIZ_TIME_PRODUCT_HOUR {
            get {
                return ResourceManager.GetString("GIZ_TIME_PRODUCT_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string GIZ_TIME_PRODUCT_HOURS {
            get {
                return ResourceManager.GetString("GIZ_TIME_PRODUCT_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GIZ_TIME_PRODUCT_MINUTES {
            get {
                return ResourceManager.GetString("GIZ_TIME_PRODUCT_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string GIZ_USER_ADDITIONAL_INFORMATION {
            get {
                return ResourceManager.GetString("GIZ_USER_ADDITIONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GIZ_USER_ADDRESS {
            get {
                return ResourceManager.GetString("GIZ_USER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available time.
        /// </summary>
        public static string GIZ_USER_AVAILABLE_TIME {
            get {
                return ResourceManager.GetString("GIZ_USER_AVAILABLE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string GIZ_USER_BASIC_INFORMATION {
            get {
                return ResourceManager.GetString("GIZ_USER_BASIC_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string GIZ_USER_BIRTH_DATE {
            get {
                return ResourceManager.GetString("GIZ_USER_BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string GIZ_USER_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("GIZ_USER_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string GIZ_USER_COUNTRY {
            get {
                return ResourceManager.GetString("GIZ_USER_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Region.
        /// </summary>
        public static string GIZ_USER_COUNTRY_REGION {
            get {
                return ResourceManager.GetString("GIZ_USER_COUNTRY_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string GIZ_USER_DETAILS {
            get {
                return ResourceManager.GetString("GIZ_USER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string GIZ_USER_FIRST_NAME {
            get {
                return ResourceManager.GetString("GIZ_USER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GIZ_USER_GENDER {
            get {
                return ResourceManager.GetString("GIZ_USER_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string GIZ_USER_HOME_PHONE {
            get {
                return ResourceManager.GetString("GIZ_USER_HOME_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string GIZ_USER_LAST_NAME {
            get {
                return ResourceManager.GetString("GIZ_USER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail and phone numbers.
        /// </summary>
        public static string GIZ_USER_MAIL_AND_PHONE_NUMBERS {
            get {
                return ResourceManager.GetString("GIZ_USER_MAIL_AND_PHONE_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string GIZ_USER_MENU_HELP {
            get {
                return ResourceManager.GetString("GIZ_USER_MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock PC.
        /// </summary>
        public static string GIZ_USER_MENU_LOCK_PC {
            get {
                return ResourceManager.GetString("GIZ_USER_MENU_LOCK_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string GIZ_USER_MENU_LOGOUT {
            get {
                return ResourceManager.GetString("GIZ_USER_MENU_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string GIZ_USER_MENU_PROFILE {
            get {
                return ResourceManager.GetString("GIZ_USER_MENU_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GIZ_USER_MENU_SETTINGS {
            get {
                return ResourceManager.GetString("GIZ_USER_MENU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Up.
        /// </summary>
        public static string GIZ_USER_MENU_USER_ONLINE_DEPOSIT {
            get {
                return ResourceManager.GetString("GIZ_USER_MENU_USER_ONLINE_DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_CLEAR {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_OR {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or enter amount*.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_OR_ENTER_AMOUNT {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_OR_ENTER_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay from PC.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_PAY_FROM_PC {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_PAY_FROM_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Next: Payment informaition.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_PLACE_NEXT {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_PLACE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-code for payment on phone.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_QR_CODE {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_QR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick select.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_QUICK_SELECT {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_QUICK_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Up.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_TITLE {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be paid:.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_TO_BE_PAID {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_TO_BE_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be credited to your Account balance.
        /// </summary>
        public static string GIZ_USER_ONLINE_DEPOSIT_WILL_BE_CREDITED {
            get {
                return ResourceManager.GetString("GIZ_USER_ONLINE_DEPOSIT_WILL_BE_CREDITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string GIZ_USER_PERSONAL_INFORMATION {
            get {
                return ResourceManager.GetString("GIZ_USER_PERSONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string GIZ_USER_POST_CODE {
            get {
                return ResourceManager.GetString("GIZ_USER_POST_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string GIZ_USER_PURCHASES {
            get {
                return ResourceManager.GetString("GIZ_USER_PURCHASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Settings.
        /// </summary>
        public static string GIZ_USER_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("GIZ_USER_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string GIZ_USER_TRANSACTIONS {
            get {
                return ResourceManager.GetString("GIZ_USER_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other users will see your username.
        /// </summary>
        public static string GIZ_USER_USERNAME_MESSAGE {
            get {
                return ResourceManager.GetString("GIZ_USER_USERNAME_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string GIZ_VERIFICATION_SEND_CODE {
            get {
                return ResourceManager.GetString("GIZ_VERIFICATION_SEND_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps page.
        /// </summary>
        public static string MODULE_PAGE_APPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_APPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string MODULE_PAGE_APPS_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_APPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games page.
        /// </summary>
        public static string MODULE_PAGE_GAMES_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_GAMES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string MODULE_PAGE_GAMES_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_GAMES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string MODULE_PAGE_HOME_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_HOME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MODULE_PAGE_HOME_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile page.
        /// </summary>
        public static string MODULE_PAGE_PROFILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_PROFILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MODULE_PAGE_PROFILE_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_PROFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop page.
        /// </summary>
        public static string MODULE_PAGE_SHOP_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_SHOP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string MODULE_PAGE_SHOP_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_SHOP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do some validation.
        /// </summary>
        public static string MODULE_PAGE_VALIDATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODULE_PAGE_VALIDATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string MODULE_PAGE_VALIDATION_TITLE {
            get {
                return ResourceManager.GetString("MODULE_PAGE_VALIDATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string ORDER_STATUS_ACCEPTED {
            get {
                return ResourceManager.GetString("ORDER_STATUS_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string ORDER_STATUS_CANCELED {
            get {
                return ResourceManager.GetString("ORDER_STATUS_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ORDER_STATUS_COMPLETED {
            get {
                return ResourceManager.GetString("ORDER_STATUS_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hold.
        /// </summary>
        public static string ORDER_STATUS_ON_HOLD {
            get {
                return ResourceManager.GetString("ORDER_STATUS_ON_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed..
        /// </summary>
        public static string PASSWORD_RESET_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not have a valid email..
        /// </summary>
        public static string PASSWORD_RESET_NO_VALID_EMAIL {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_NO_VALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not have a valid phone..
        /// </summary>
        public static string PASSWORD_RESET_NO_VALID_MOBILE {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_NO_VALID_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        public static string PASSWORDS_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORDS_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number field is required..
        /// </summary>
        public static string PHONE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("PHONE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message delivery impossible, check configuration..
        /// </summary>
        public static string PROVIDER_NO_ROUTE_FOR_DELIVERY {
            get {
                return ResourceManager.GetString("PROVIDER_NO_ROUTE_FOR_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Contact front desk for info..
        /// </summary>
        public static string REGISTER_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("REGISTER_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select something.
        /// </summary>
        public static string SELECT_SOMETHING {
            get {
                return ResourceManager.GetString("SELECT_SOMETHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string SEX_FEMALE {
            get {
                return ResourceManager.GetString("SEX_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string SEX_MALE {
            get {
                return ResourceManager.GetString("SEX_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string SEX_UNSPECIFIED {
            get {
                return ResourceManager.GetString("SEX_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry with SMS.
        /// </summary>
        public static string UI_RETRY_WITH_SMS {
            get {
                return ResourceManager.GetString("UI_RETRY_WITH_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset value.
        /// </summary>
        public static string UNSET_STRING_VALUE {
            get {
                return ResourceManager.GetString("UNSET_STRING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the e-mail you’d like to use. To make sure this e-mail is yours, will send you a verification code..
        /// </summary>
        public static string UPDATE_EMAIL_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_EMAIL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent you an e-mail with a code. Enter it to verify your e-mail..
        /// </summary>
        public static string UPDATE_EMAIL_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_EMAIL_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update number.
        /// </summary>
        public static string UPDATE_NUMBER {
            get {
                return ResourceManager.GetString("UPDATE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number you’d like to use. To make sure this number is yours, will send you a verification code..
        /// </summary>
        public static string UPDATE_NUMBER_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_NUMBER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent you an SMS with a code. Enter it to verify your phone..
        /// </summary>
        public static string UPDATE_NUMBER_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_NUMBER_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code to Continue.
        /// </summary>
        public static string USER_LOCK_SCREEN_ENTER_CODE {
            get {
                return ResourceManager.GetString("USER_LOCK_SCREEN_ENTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot PIN.
        /// </summary>
        public static string USER_LOCK_SCREEN_FORGOT_PIN {
            get {
                return ResourceManager.GetString("USER_LOCK_SCREEN_FORGOT_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Lock is currently on.
        /// </summary>
        public static string USER_LOCK_SCREEN_LOCKED_SUBTITLE {
            get {
                return ResourceManager.GetString("USER_LOCK_SCREEN_LOCKED_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you PIN to access this profile.
        /// </summary>
        public static string USER_LOCK_SCREEN_LOCKED_TITLE {
            get {
                return ResourceManager.GetString("USER_LOCK_SCREEN_LOCKED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock this profile by creating a 4-digit pin. Memorize or write it down..
        /// </summary>
        public static string USER_LOCK_SCREEN_SUBTITLE {
            get {
                return ResourceManager.GetString("USER_LOCK_SCREEN_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Lock.
        /// </summary>
        public static string USER_LOCK_SCREEN_TITLE {
            get {
                return ResourceManager.GetString("USER_LOCK_SCREEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount is {0}..
        /// </summary>
        public static string USER_ONLINE_DEPOSIT_MAXIMUM_AMOUNT_IS {
            get {
                return ResourceManager.GetString("USER_ONLINE_DEPOSIT_MAXIMUM_AMOUNT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount is {0}..
        /// </summary>
        public static string USER_ONLINE_DEPOSIT_MINIMUM_AMOUNT_IS {
            get {
                return ResourceManager.GetString("USER_ONLINE_DEPOSIT_MINIMUM_AMOUNT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field has an incorrect date value..
        /// </summary>
        public static string VALIDATION_ERROR_INVALID_DATE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be lesser than {0}.
        /// </summary>
        public static string VALIDATION_ERROR_MAX_DATE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MAX_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string VALIDATION_ERROR_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified email address is already in use.
        /// </summary>
        public static string VE_EMAIL_ADDRESS_USED {
            get {
                return ResourceManager.GetString("VE_EMAIL_ADDRESS_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate email..
        /// </summary>
        public static string VE_ERROR_CANNOT_VALIDATE_EMAIL {
            get {
                return ResourceManager.GetString("VE_ERROR_CANNOT_VALIDATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate phone..
        /// </summary>
        public static string VE_ERROR_CANNOT_VALIDATE_PHONE {
            get {
                return ResourceManager.GetString("VE_ERROR_CANNOT_VALIDATE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check create account token validity error..
        /// </summary>
        public static string VE_ERROR_CANNOT_VALIDATE_RECOVERY_TOKEN {
            get {
                return ResourceManager.GetString("VE_ERROR_CANNOT_VALIDATE_RECOVERY_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check password recovery token validity error..
        /// </summary>
        public static string VE_ERROR_CANNOT_VALIDATE_REGISTRATION_TOKEN {
            get {
                return ResourceManager.GetString("VE_ERROR_CANNOT_VALIDATE_REGISTRATION_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate username..
        /// </summary>
        public static string VE_ERROR_CANNOT_VALIDATE_USERNAME {
            get {
                return ResourceManager.GetString("VE_ERROR_CANNOT_VALIDATE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified mobile phone number is already in use.
        /// </summary>
        public static string VE_MOBILE_PHONE_USED {
            get {
                return ResourceManager.GetString("VE_MOBILE_PHONE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username is already in use.
        /// </summary>
        public static string VE_USERNAME_USED {
            get {
                return ResourceManager.GetString("VE_USERNAME_USED", resourceCulture);
            }
        }
    }
}
